Laravel5/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as' => '/',
    'uses' => 'PagesController@getIndex'
]);

Route::get('about', [
    'as' => 'about',
    'uses' => 'PagesController@getAbout'
]);

Route::get('contact', [
    'as' => 'contact',
    'uses' => 'PagesController@getContact'
]);

Route::get('help', [
    'as' => 'help',
    'uses' => 'PagesController@getHelp'
]);

Route::resource('product','ProductController');

Route::get('basicrouting', function(){
  return view('welcome');
});

Route::match(['get', 'post', 'delete'], 'matchrouting', function(){
  return 'Match routing';
});

Route::any('anyroute', function(){
  return 'Any route';
});

Route::get('user/{id}&album/{albumId}', function($id, $albumId){
  return $id.' '.$albumId;
});

Route::get('album/{id?}', function($id = null){
  return $id;
});

Route::get('user/{id}', function($id){
  return $id;
})
->where('ide', '[0-9]+');

Route::get('namedRoutes', [
  'as' => 'namedRoutes',
  'uses' => 'PagesController@getIndex'
]);

Route::group(['as' => 'admin::', 'prefix' => 'admin'], function(){
  Route::get('dashboard', [
    'as' => 'dashboard',
    'uses' => 'PagesController@getDashboard'
  ]);

  Route::get('reports', [
    'as' => 'reports',
    'uses' => 'PagesController@getReports'
  ]);

});


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

Laravel5/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
  protected $fillable = [
    'name',
    'price'
  ];

  public $timestamps = false;

  protected $table = 'products';
}

Laravel5/app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

Laravel5/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Laravel5/app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Controllers\Controller;

class PagesController extends Controller
{
  public function getIndex(){
    return view('welcome');
  }

  public function getAbout(){
    $companyName = "Code Executable";
    $isUserRegistered = false;

    $users = array("Renato","Erik","John","Samantha");

    return view('pages.about')
      ->with("companyName", $companyName)
      ->with("isUserRegistered", $isUserRegistered)
      ->with("users", $users);
  }

  public function getContact(){
    return view('pages.contact');
  }

  public function getHelp(){
    return view('pages.help');
  }

  public function getTest($id){
    return $id;
  }

  public function getDashboard(){
    return 'dashboard';
  }

  public function getReports(){
    return 'reports';
  }

}

Laravel5/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Product;

class ProductController extends Controller
{
  /**
  *Display a listening of the resource.
  *
  *@return \Illuminate\Http\Response
  */

  public function index(){
    $products = Product::all();
    // return $products;
    return view('products.index')->with("products", $products);
  }

  /**
  *Show the form for creating a new resource.
  *
  *@return \Illuminate\Http\Response
  */
  public function create(){
    return view('products.create');
  }

  /**
  *Store a newly created resource in storage.
  *
  *@param \Illuminate\Http\Request  $request
  *@return \Illuminate\Http\Response
  */

  public function store(Request $request){
    //First method to store a product
    // $product = new Product;
    // $product->name = $request->name;
    // $product->price = $request->price;
    // $product->save();

    //Second method
    $inputs = $request->all();
    $product = Product::Create($inputs);

    return redirect()->action('ProductController@index');
    // return redirect()->route('product.index');
  }

  /**
  *Display the specified resource.
  *
  *@param int $id
  *@return \Illuminate\Http\Response
  */

  public function show($id){
    $product = Product::find($id);

    return view('products.show')->with('product', $product);
  }

  /**
  *Show the form for editing the specified resource.
  *
  *@param int $id
  *@return \Illuminate\Http\Response
  */

  public function edit($id){
    $product = Product::find($id);

    // return view('products.edit')->with('product', $product);
    return view('products.edit', compact('product', $product));
  }

  /**
  *Update the specified resource in storage
  *
  *@param \Illuminate\Http\Request $request
  *@param int $id
  *@return \Illuminate\Http\Response
  */

  public function update(Request $request, $id){
    $product = Product::find($id);

    $product->name = $request->name;
    $product->price = $request->price;
    $product->save();

    return redirect()->route('product.index');
  }

  /**
  *Remove the specified resource from storage
  *
  *@param int $id
  *@return \Illuminate\Http\Response
  */

  public function destroy($id){
    // Product::destroy($id);
    $product = Product::find($id)->deleted();

    return redirect()->route('product.index');
  }

}

Laravel5/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>@yield('title')</title>
  </head>

  <body>
    @include('layouts.menu')
    <!--@include('layouts.sidebarleft')-->
    @yield('body')
  </body>
</html>

Laravel5/resources/views/layouts/menu.blade.php
<ul>
  <li>Home</li>
  <li>Login</li>
  <li>About</li>
  <li>Contact</li>
</ul>

Laravel5/resources/views/pages/about.blade.php
@extends('layouts.layout')
@section('tittle')
  About
@stop

@section('body')
  <h1>This is the about page.</h1>

  <p>{{$companyName}}</p>

  @if($isUserRegistered == true)
    <p>Hello mate!</p>
  @else
    <p>Please register!</p>
  @endif

  @for($i=0; $i<10; $i++)
    <p>The current value is {{$i}}</p>
  @endfor

  @foreach($users as $data)
    {{$data}}<br>
  @endforeach
@stop

Laravel5/resources/views/pages/contact.blade.php
@extends('layouts.layout')

@section('tittle')
  Contact us
@stop

@section('body')
  <h1>This is the contact page.</h1>
    <input type="text">
    <!-- {!! Form::text('price') !!} -->
    {!! Form::text('price', '50$',[
      'class' => "form-control",
      'placeholder' => "Give a price"
    ]) !!}

    {!! Form::number('level', 10, [
      'max' => 20,
      'min' => -5
    ]) !!}

@stop

Laravel5/resources/views/pages/help.blade.php
@extends('layouts.layout')

  @section('tittle')
    Help
  @stop

  @section('body')
    <h1>This is the help page.</h1>
  @stop

Laravel5/resources/views/products/create.blade.php
@extends('layouts.layout')

@section('title')
  Create New Product
@stop

@section('body')
  {!!Form::open(['route' => 'product.store']) !!}

  {!!Form::label('name', 'Name')!!}
  {!!Form::text('name', null, ['placeholder' => "Give a name"])!!}

  {!!Form::label('price', 'Price')!!}
  {!!Form::text('price', null, ['placeholder' => "Give a price"])!!}

  {!!Form::submit('Create')!!}

  {!! Form::close() !!}
@stop

Laravel5/resources/views/products/edit.blade.php
@extends('layouts.layout')

@section('title')
  Edit {$product->name}
@stop

@section('body')
  {!! Form::model($product,[
    'method' => 'patch',
    'route' => ['product.update', $product->id]
    ])!!}

    {!!Form::label('name', 'Name')!!}
    {!!Form::text('name', $product->name, ['placeholder' => "Give a name"])!!}

    {!!Form::label('price', 'Price')!!}
    {!!Form::text('price', $product->price, ['placeholder' => "Give a price"])!!}

  {!!Form::submit('Edit')!!}
  {!!Form::close()!!}
@stop

Laravel5/resources/views/products/index.blade.php
@extends('layouts.layout')

@section('title')
  All products
@stop

@section('body')
  @foreach($products as $product)
    <h1>{{$product->name}}</h1>
    <h3>{{$product->price}}</h3>
    <br>
  @endforeach

  <a href="{{url('basicrouting')}}">Basic Routing</a>
  <a href="{{route('about')}}">About</a>
  <a href="{{route('product.create')}}">Create</a>

  <a href="{{route('test', ['id' => 15])}}">Test</a>
@stop

Laravel5/resources/views/products/show.blade.php
@extends('layouts.layout')

@section('title')
  {$product->name}
@stop

@section('body')
  {!! Form::open([
    'method' => 'delete',
    'route' => ['product.destroy', $product->id]
    ])!!}
  <h1>{{$product->name}}</h1>
  <h3>{{$product->price}}</h3>

  <pre>
    <a href="{{route('product.edit', $product->id)}}">Edit</a>  {!!Form::submit('Delete')!!}
    <!-- <a href="{{route('product.destroy', $product->id)}}">Delete</a> -->
  </pre>
  {!!Form::close()!!}
@stop